name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12', '3.13']
    # Let 3.13 be "allowed to fail" while 3.12 is required
    continue-on-error: ${{ matrix.python-version == '3.13' }}

    env:
      # Keep your current CI flags
      SKIP_FIREBASE_INIT: "1"   # skip Firebase Admin init in CI
      ALLOW_DEV_AUTH: "1"       # enable X-Uid/X-Email/X-Admin path in CI
      PYTHONPATH: "."
      # Also support alt gating if your code uses this
      USE_FAKE_DB: "1"
      PYTHONDONTWRITEBYTECODE: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=app --cov-report=xml

      # Upload coverage only once (from 3.12 job)
      - name: Upload coverage to Codecov
        if: ${{ matrix.python-version == '3.12' && !cancelled() }}
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
